package model;

public enum TypeMessage {
    MESSAGE,
    FILE,
    AUDIO,
    VIDEO,
    CALL_REQUEST,
    CALL_ACCEPT,
    CALL_REJECT,
    USER_ONLINE,
    USER_OFFLINE,
    MESSAGE_DELIVERED,
    MESSAGE_SEEN,
    CONNECT,
    DISCONNECT,
    GET_USERS,
    GET_CONTACTS,
    ADD_CONTACT,
    REMOVE_CONTACT,
    GET_HISTORIQUE
}